# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/baml-0.1.0-x86_64/all/baml-0.1.0-x86_64.rbi
#
# baml-0.1.0-x86_64-linux

class Baml::BamlRuntime
  def call_function(arg0); end
  def self.from_directory(arg0); end
end
module Baml
  def json_to_ruby(arg0); end
  def self.json_to_ruby(arg0); end
end
