###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ bundle add baml sorbet-runtime sorbet-coerce sorbet-struct-comparable
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# frozen_string_literal: true
# rubocop: disable
# formatter:off
# typed: false
require "sorbet-struct-comparable"
require "sorbet-runtime"

require_relative "types"

module Baml
  
  module PartialTypes
    class Email < T::Struct; end
    class MessageFeatures < T::Struct; end
    class OrderInfo < T::Struct; end
    class Email < T::Struct
      include T::Struct::ActsAsComparable
      const :subject, T.nilable(String)
      const :body, T.nilable(String)
      const :from_address, T.nilable(String)
    end
    class MessageFeatures < T::Struct
      include T::Struct::ActsAsComparable
      const :categories, T::Array[T.nilable(Baml::Types::Category)]
    end
    class OrderInfo < T::Struct
      include T::Struct::ActsAsComparable
      const :order_status, T.nilable(Baml::Types::OrderStatus)
      const :tracking_number, T.nilable(String)
      const :estimated_arrival_date, T.nilable(String)
    end
  end
end