name: Ruby Workflow

on:
  push:
    branches:
      - main

jobs:
  ruby:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: x86_64-linux
            runs-on: ubuntu-latest

          - name: arm64-darwin
            runs-on: macos-14

          - name: x86_64-darwin
            runs-on: macos-13

        ruby-version:
          - 3.3
          - 3.2
          - 3.1

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install dependencies
        run: |
          bundle install

      - name: Run Ruby script
        run: |
          bundle exec ruby examples.rb
        env:
          OPEN_API_KEY: ${{ secrets.OPEN_API_KEY }}